#!/bin/bash

# Funcție pentru setarea parolei master
set_master_password() {
    local account_name="$1"
    read -s -p "Introduceți parola master: " master_password
    echo "$master_password" > "$account_name.txt"
    echo
    echo "Parola master a fost setată cu succes."
}

# Funcție pentru adăugarea unei parole
add_password() {
    local account_name="$1"
    read -p "Introduceți numele parolei: " password_name
    read -s -p "Introduceți valoarea parolei: " password_value
    echo "$password_name: $password_value" >> "$account_name.txt"
    echo
    echo "Parola \"$password_name\" a fost adăugată cu succes în baza de date."
}

# Funcție pentru actualizarea unei parole
update_password() {
    local account_name="$1"
    read -p "Introduceți numele parolei pe care doriți să o actualizați: " password_name
    read -s -p "Introduceți noua valoare a parolei: " new_password_value
    sed -i "s/^$password_name: .*/$password_name: $new_password_value/g" "$account_name.txt"
    echo
    echo "Parola \"$password_name\" a fost actualizată cu succes."
}

# Funcție pentru ștergerea unei parole
delete_password() {
    local account_name="$1"
    read -p "Introduceți numele parolei pe care doriți să o ștergeți: " password_name
    sed -i "/^$password_name: /d" "$account_name.txt"
    echo
    echo "Parola \"$password_name\" a fost ștearsă cu succes."
}

# Funcție pentru listarea parolelor
list_passwords() {
    local account_name="$1"
    echo "Parolele stocate în baza de date:"
    cat "$account_name.txt"
}

# Funcție pentru generarea unei parole puternice
generate_password() {
    local account_name="$1"
    read -p "Introduceți numele parolei: " password_name
    password_value=$(openssl rand -base64 12)
    echo "$password_name: $password_value" >> "$account_name.txt"
    echo
    echo "Parola \"$password_name\" a fost generată cu succes."
}

# Funcție pentru crearea unui cont nou
create_account() {
    echo "Creați un cont nou"
    read -p "Introduceți numele contului: " account_name

    # Verificăm dacă contul există deja
    if [ -e "$account_name.txt" ]; then
        echo "Contul \"$account_name\" există deja."
    else
        # Creăm fișierul de cont și setăm parola master
        touch "$account_name.txt"
        set_master_password "$account_name"
        echo "Contul \"$account_name\" a fost creat cu succes."

        # Adăugăm o parolă inițială
        add_password "$account_name"

        while true; do
            echo "Ce doriți să faceți în continuare?"
            echo "1. Adăugați o parolă nouă"
            echo "2. Actualizați o parolă existentă"
            echo "3. Ștergeți o parolă existentă"
            echo "4. Listați parolele stocate"
            echo "5. Generați o parolă puternică"
            echo "6. Ieșiți"

            read -p "Introduceți opțiunea dorită: " option

            case $option in
                1)
                    add_password "$account_name"
                    ;;
                2)
                    update_password "$account_name"
                    ;;
                3)
                    delete_password "$account_name"
                    ;;
                4)
                    list_passwords "$account_name"
                    ;;
                5)
                    generate_password "$account_name"
                    ;;
                6)
                    break
                    ;;
                *)
                    echo "Opțiune invalidă. Vă rugăm să selectați o opțiune validă."
                    ;;
            esac
        done
    fi
}

# Apelăm funcția pentru crearea unui cont nou
create_account
